iovisor/gobpf

bpf_module.go
Re-add the `AttachKretprobe` from
https://github.com/iovisor/iomodules/commit/9da230746e2b90f9c4d3e22f7211e904e2a17d16
Signed-off-by: Michael Schubert <michael@kinvolk.io>
=> bpf_module: include `AttachKretprobe`

elf/elf.go, elf/module_unsupported.go
add missing function in _unsupported.go.
-----
@schu @iaguis PTAL
Notes: I tested with:
- https://github.com/weaveworks/tcptracer-bpf/pull/4
- https://github.com/kinvolk/scope/commits/alban/conn-perf-ebpf-guess-ci-assets
=> elf: fixup NewModuleFromReader

examples/perf.go
I think that using the TableId function instead of a fixed number makes the example a little bit more clear for the users.
=> Example: use TableId instead of fixed id

bcc/perf.go
Newer versions of go (1.8+) are more strict about this, so the
compilation failed:
```
github.com/iovisor/gobpf/bcc
bcc/perf.go:131: cannot use reader (type unsafe.Pointer) as type *C.struct_perf_reader in argument to func literal
```
Cast it explicitly.
=> bcc: cast reader explicitly

elf/module.go, elf/module_unsupported.go
We are discussing adding a way to specify the maxactive field of a
kretprobe in the kernel:
https://github.com/iovisor/bcc/issues/1072#issuecomment-289777787
How do we expose this in gobpf? I see two possible ways:
- at build-time: `SEC("kretprobe?maxactive=128/inet_csk_accept")`
- at run-time: `m.EnableKprobe("kretprobe/inet_csk_accept", 128)`
This patch implements it at run-time. This might not not ideal because `EnableKprobes` (plural) would use the same maxactive for all kretprobes.
/cc @iaguis @schu
TODO:
=> kretprobes: set maxactive

elf/elf_unsupported.go, elf/perf.go, examples/perf.go
Some fixes for https://github.com/iovisor/gobpf/issues/42
=> elf: perf ordering fixes

bpf_test.go, elf/elf.go, elf/elf_unsupported.go, elf/perf.go
Callers of b.Load() can optionally specifies parameters for each ELF section. This patch adds the following two parameters:
- PerfRingBufferPageCount. Default: 8 pages
- SkipPerfMapInitialization: Default: false
Useful for https://github.com/weaveworks/tcptracer-bpf/pull/37
=> perf maps: add configurable parameters

elf/perf.go
Otherwise we block and do nothing.
Fixup for c520ae517435b1a4e01915b2f31004b60ff68600
=> elf: add missing select default

bpffs/fs.go
I get error `bpffs/fs.go:20: constant 3405662737 overflows int32` in ARM, see https://circleci.com/gh/weaveworks/scope/7239
=> Fix compilation error in 32-bit architectures

README.md, elf/elf.go, elf/module.go
We follow kernel's convention of taking sections that start with
"socket".
Also, rework cgroup API for consistency.
=> elf: add socket filter support

elf/module.go
We were doing it for `NewModule()` but not for `NewModuleFromReader()`.
=> elf: add missing cgroup and socket filter maps initialization

bcc/module.go, bcc/symbol.go, examples/bcc/bash_readline/bash_readline.go, examples/bcc/strlen_count/strlen_count.go
Hi,
This PR adds supports for tracing uprobes.
It includes some new functions used to query the symbol cache for the location (file and offset) of function within userland code; and to retrieve a list of matching symbols (functions) from a given module (library or binary) to allow attaching to all symbols that match a certain pattern. (Both these ideas borrowed heavily from the Python implementation).
It also adds functions to the Module type to allow adding of uprobes, uretprobes, and all those that match a pattern.
Finally an example, strlen_count.go, of how to use these new functions.
I do have a query/problem that I could do with some advice on, regarding the example:
I have used a Table without a PerfMap (in contrast to the other example which is given). The tracing happens until the …
=> Add support for uprobes

semaphore.sh
The KVM stage1 is limited to 128MB by default:
https://coreos.com/rkt/docs/latest/running-kvm-stage1.html#memory
Raise the limit to avoid OOMs during test runs.
=> semaphore.sh: raise rkt memory limit

elf/elf.go, elf/module.go
Trying to close it was making `Module.Close()` fail for Kprobes that
weren't enabled.
=> elf: don't close event FD if Kprobe wasn't enabled

elf/perf.go
Go channels should always be closed on the sender side. Also, fix the
comment that says otherwise.
When synchronously sending an event, check if it's time to close instead
of blocking indefinitely.
-----
/cc @schu @iaguis @2opremio
=> perf: close channels on the sender side & fix closing race

elf/module.go
Before, `tracepointPrograms` was missing from on `NewModuleFromReader`.
=> elf: unify `NewModule*`

elf/module.go
The bpf() syscall has a log_buf parameter for the verifier to write
output. When the buffer is too small, bpf() fails, even if the program
is good otherwise.
Symptoms:
error while loading "kretprobe/foobar" (no space left on device)
Changing the size from 64K to 256K works for me in practice
=> Increase size of log buffer

elf/module.go
0e0349c already increased the log buffer but while testing on kernel
4.4 I ran out of buffer space again.
Let's try with 512k. Hopefully this is enough.
=> elf: increase size of log buffer again

bpf_test.go, elf/elf.go
Remove an unnecessary error check in `elfReadVersion()`. The error is already being checked above in the same function, https://github.com/iovisor/gobpf/blob/master/elf/elf.go#L284
We should check for a specific error code `os.ErrInvalid`, instead of comparing error strings with each other.
=> elf,bpf_test: Improve error checks

elf/elf.go
In case of an invalid instruction, `relocate()` prints out only an ambiguous error message `"invalid relocation"`. We should at least print out instruction code, symbol name, as well as essential fields of the ELF section header. For example:
```
invalid relocation: instruction code=0x85
symbol section: Name=.text, Type=SHT_PROGBITS, Flags=SHF_ALLOC+SHF_EXECINSTR
```
=> elf: print out precise error message of invalid relocation

elf/module.go
Enable users to look at the verifier log if they want.
=> elf: add accessor for log buf

bcc/module.go, bcc/perf.go, bcc/symbol.go, semaphore.sh
(Work-in-progress, please do not merge. After bcc 0.4 has been released, I will get back to this PR.)
Fix build problems in `bcc/symbol.go` and `bcc/perf.go` when using bcc 0.4.
* As `bcc_foreach_symbol()` was renamed to `bcc_foreach_function_symbol()` since https://github.com/iovisor/bcc/commit/fcb2ed8e5895, we should conditionally run different functions. bcc04: `bcc_foreach_function_symbol`, !bcc: `bcc_foreach_symbol`
* As prototype of `bcc_resolve_symname()` was changed to include `bcc_symbol_option` since https://github.com/iovisor/bcc/commit/aff6ce7075da, we should contidionally use different function prototypes. bcc04: with `bcc_symbol_option`, !bcc: without `bcc_symbol_option`.
* As prototype of `bcc_open_perf_buffer()` was changed to include `perf_reader_lost_cb` since …
=> bcc: fix build issues when using bcc 0.4

bcc/symbol.go
5eb85ff7f92d9ea4d0ab5cb3e9b44437d5a40dd6 updated `bcc_resolve_symname`
to a new function signature with a parameter `bcc_symbol_option` (as
found in bcc v0.4.0), but didn't populate the symbol options with
meaningful default values. As a consequence, symbols were not
resolved, e.g.
```
$ sudo -E go run examples/bcc/bash_readline/bash_readline.go
Failed to attach return_value: unable to locate symbol readline in module /bin/bash: unable to locate symbol readline in module /bin/bash: <nil>
exit status 1
```
Revert that part of the update and pass `nil` which makes bcc use the
default options.
=> bcc: use default options for `bcc_resolve_symname`

bpf_test.go, elf/module.go
This fixes the error returned while trying to detach
" detaching BPF socket filter: invalid argument"
=> Fix DetachSocketFilter

bcc/module.go, semaphore.sh
Note that `bpf_prog_load` as in bcc 0.5.0 prints the log buf to stderr in any case, even when successful, i.e. there's no way currently to suppress output as far as I have seen. In master this was already changed to only print when `ret < 0`: https://github.com/iovisor/bcc/commit/c669257c1f16eae4c695866bea147f57a9092b80 Ideally, we would be able to disable output entirely.
=> Update to bcc 0.5.0

bcc/module.go
AttachUretprobe must prefix with `r_`, not `p_` in order for uretprobes to work.
With this stupid patch, the probes are now correct (via perf probe -l)
```
$ sudo perf probe -l
uprobes:p__usr_local_lib_XXX_bcc_XXX (on SomeFunction in /usr/local/lib/libXXX)
uprobes:r__usr_local_lib_XXX_bcc_XXX (on SomeFunction%return in /usr/local/lib/libXXX)
```
=> AttachUretprobe prefix with r_, not p_

bcc/table.go, bpf_test.go
This PR adds a `DeleteAll` function to be able to easily clear all keys of a table. Idea is to have something like https://github.com/iovisor/bcc/blob/master/docs/reference_guide.md#5-clear.
Not quite sure what's the contribution process so let me know if there is something else I have to do here.
=> bcc: add Table.DeleteAll

bcc/module.go, examples/bcc/xdp/xdp_drop.go
Currently, logging is always enabled (log level `1`) and the log buffer
set to a fixed size of 65536 bytes. Since the log buffer must be large
enough for all verifier message when logging is enabled, the code
returns `ENOSPC` for larger programs and doesn't allow the user to
disable logging or increase the buffer.
Instead, disable bpf logging by default and allow the user to specify
log level and buffer size on `Load()`. This way, users can specify a
large enough buffer matching their program if desired.
Also, add a missing error check in `examples/bcc/xdp/xdp_drop.go`.
Resolves #103
=> bcc: make logging configurable

semaphore.sh
Use the latest longterm kernels.
Also, update the rkt version used to v1.29.
=> semaphore: update kernels to test on

pkg/progtestrun/prog_test_run.go
It's not possible to check for the presence of BPF_PROG_TEST_RUN
using the pre-processor, since it is an enum. Instead, check that
the kernel we are compiling against is at least 4.12.0.
=> pkg/progtestrun: Fix conditional compilation

bcc/perf.go, bcc/table.go, bpf_test.go, examples/bcc/strlen_count/strlen_count.go, examples/bcc/xdp/xdp_drop.go
Currently `bcc.Table` provides iteration using a channel, a pattern that causes high overhead, and also always converts values to and from strings, which is inconvenient. This PR changes that API to a cursor-like iterator, providing a `Next()` method for iteration, and `Key()`, `Leaf()` to access the raw byte-slices, as well as `KeyString()`, `LeafString()` to continue supporting simple printing of table contents.
Note: Given that this is already a breaking API change, we'd offer to merge parts of @nathanleclaire's PR #102, which would change the regular `Get` and `Set` methods to use byte-slices as well.
=> bcc.Table API: Use iterator instead of channel, provide raw byte-slices

bcc/module.go, bcc/symbol.go
Some kernel versions use `sys_` as the prefix for function names,
but newer kernels use `__x64_sys_`. This function can be used to load a
specific function name based in the kernel version.
For example:
```
m := bpf.NewModule(source, []string{})
defer m.Close()
fnname := m.GetSyscallFnName("execve")
```
Signed-off-by: David Calavera <david.calavera@gmail.com>
=> Add function to get a syscall function name by kernel version.

pkg/bpffs/fs.go
The default mountpoint for BPFFS is /sys/fs/bpf, but mounting BPFFS
in the other locations is also possible. This change provides
additional functions which allow to do that.
Signed-off-by: Michal Rostecki <mrostecki@suse.de>
=> bpffs: Allow to mount with custom mountpoint

bpf_test.go
As is, a failure during bpffs mount whould silently skip all elf tests
and make the test run look successful judging from its status.
=> bpf_test: don't skip when bpffs can't be mounted

pkg/ksym/ksym.go, pkg/ksym/ksym_test.go
This PR is based on https://github.com/iovisor/gobpf/pull/105 but adds the `Ksym` function in a helper package.
People found this kind of helpers pretty useful in the Python library. See : https://github.com/iovisor/gobpf/issues/113
cc @bobrik
=> Add ksym helper

bcc/table.go
Change snake_case to camelCase to match code convention.
Thanks.
=> Match code convention, snake_case to camelCase

bcc/table.go, bpf_test.go
This PR adds SetP,GetP,DeleteP to Table for handling key/leaf as unsafe.Pointer.
It is useful if we use `struct` for key or leaf of bpf table.
```
func (table *Table) GetP(key unsafe.Pointer) (unsafe.Pointer, error)
func (table *Table) SetP(key, leaf unsafe.Pointer) error
func (table *Table) DeleteP(key unsafe.Pointer) error
```
=> bcc: add SetP,GetP,DeleteP to Table for handling key/leaf as unsafe.Pointer

bcc/module.go
This can be used with `perf` when `net.core.bpf_jit_kallsyms=1`
and `--kallsyms=/proc/kallsyms` are passed to `perf record`.
On newer kernels `perf top` can also accept `--kallsyms`:
* https://www.spinics.net/lists/linux-perf-users/msg07216.html
See: https://github.com/cloudflare/ebpf_exporter/issues/39
=> Implement GetProgramTag

elf/elf.go
Allow to override max_entries for BPFMap through BPFMapMaxEntries SectionParams attribute.
In the case where we want to store network connections in a BPF Map, what we could do would be to get the maximum number of connections that can be running on the given host and use it to set the BPF map size.
=> elf: allow to override max_entries for BPFMap

elf/module.go
**Issue:** users of the elf module api are not able to loop over sched progs. The'd have to know the program name upfront.
This PR offers an func that returns a channel that emits the sched programs included in the module. Just like the other `Iter*` funcs.
Users have the very same issue with accessing maps. Would you like to have that added aswell?
=> elf: add implementation to loop sched progs

bpf_test.go, elf/table.go
Per the [documentation](http://man7.org/linux/man-pages/man2/bpf.2.html) on `BPF_MAP_GET_NEXT_KEY `:
> If key is found, the operation returns zero and sets the
next_key pointer to the key of the next element.  If key is
not found, the operation returns zero and sets the next_key
pointer to the key of the first element.  If key is the last
element, -1 is returned and errno is set to ENOENT.  Other
possible errno values are ENOMEM, EFAULT, EPERM, and EINVAL.
This method can be used to iterate over all elements in the
map.
This PR fixes `LookupNextElement` to not return an error when `ENOENT` is received. 
We noticed that the errors being created here were a minor, but persistent, source of allocations in our application.
We're also seeing similar allocation patterns in `LookupElement` / …
=> [elf] LookupNextElement should not return an error on ENOENT 

elf/elf.go, elf/module.go, elf/pinning.go, pkg/progtestrun/prog_test_run.go
Using plain initialization list for a union with nested anonymous
structs works incorrectly with Clang.  `syscall()` in `bpf_update_element()`
may fail if `bpf_attr` is improperly initialized.  Initialization with
`memset()` is more portable.
=> Fix bpf_attr initialization

elf/module.go
Current error when running a go binary using this lib:
```
warning: implicit declaration of function ‘memset’ [-Wimplicit-function-declaration]
memset(&attr, 0, sizeof(attr));
^~~~~~
```
PR #207 fixed/improved the `union bpf_attr` initialization using `memset`, but forgot to include `string.h` in elf/module.go (while in elf/elf.go there already was, and in elf/pinning.go was added)
Signed-off-by: Leonardo Di Donato <leodidonato@gmail.com>
=> string.h inclusion needed in module.log for memset

README.md, bpf_test.go, elf/elf.go, elf/include/libbpf.h, elf/include/nlattr.h, elf/lib/netlink.c, elf/lib/nlattr.c, elf/module.go, tests/dummy.c
This PR brings the support for XDP programs in ELF object files through `SEC(xdp/...)` annotations.
It allows for definition of multiple XDP programs in the same C source file. Once ELF module is instantiated/loaded, you can call `AttachXDP` passing the network device and the name of the XDP program you would like to attach on the interface. The XDP programs can be unloaded from the network device via `RemoveXDP` method.
=> Support for XDP programs in ELF object files

elf/table.go
To enable build on old build servers with an outdated `/usr/include/linux/bpf.h`, use gobpf's copy instead.
=> elf: include gobpf's bpf.h instead of host's

elf/module.go
Add getter function to get the file descriptor of a tracepoint program.
It can be used in the following way:
```
for tp := range m.IterTracepointProgram() {
fmt.Printf("name: %s fd=%d\n", tp.Name, tp.Fd())
}
```
=> elf: TracepointProgram: add Fd()

elf/perf.go, elf/perf_unsupported.go
NowNanoseconds() is a useful helper func in apps that track, e.g.,
time delta to a time stamp set (using bpf_ktime_get_ns()) by eBPF.
Fixes: #213
=> elf: export NowNanoseconds

elf/kernel_version.go, elf/kernel_version_test.go
This fixes the parsing of the `/proc/version` file for some debian versions.
This was causing `bpf_prog_load` to fail on [this check](https://elixir.bootlin.com/linux/v4.4/source/kernel/bpf/syscall.c#L630).
The fix is to add an optional group after the kernel version to match a commit hash (multiple alphanumeric characters).
=> fix: Debian version regex can fail on some debian versions if the commit sha is appended to the version

elf/include/bpf.h, elf/table.go
elf/include/bpf.h: update header from kernel sources
Picked from Linux 5.0: https://github.com/torvalds/linux/blob/v5.0/include/uapi/linux/bpf.h
```
curl https://raw.githubusercontent.com/torvalds/linux/v5.0/include/uapi/linux/bpf.h > elf/include/bpf.h
```
This defines `BPF_MAP_TYPE_QUEUE` among other things.
Implement LookupAndDeleteElement
On syscall side, `BPF_MAP_TYPE_QUEUE`'s elements can only be read by `BPF_MAP_LOOKUP_AND_DELETE_ELEM`.
This patch implements it with LookupAndDeleteElement().
=> Add map queue support

elf/elf.go
This stops the BPF program from writing into the perf ring buffers. However, the userspace program can still read the ring buffers.
=> elf: implement PerfMapStop

bcc/perf.go, elf/perf_unsupported.go, examples/bcc/bash_readline/bash_readline.go, examples/bcc/execsnoop/execsnoop.go, examples/bcc/perf/perf.go
this PR adds support for handling lost events using a dedicated channel, similar to how regular events are handled.
a future PR can update the examples to utilize this feature. at the moment I just passed nil which does no change to existing functionality.
=> add lost events channel

elf/elf_unsupported.go
This allows avoiding syntax errors on non-Linux systems. Resolves #238.
=> Add dummy Map.Fd() implementation

bcc/symbol.go
This function calls `bcc_symcache_new` which creates an [internal instance of the cache](https://sourcegraph.com/github.com/iovisor/bcc@d2e8ea4/-/blob/src/cc/bcc_syms.cc#L520), but doesn't release it.
=> fix memory leak in bccResolveName

bcc/module.go
The syscall prefix cannot change on same system, so it's wasteful to re-calculate it.
=> cache syscall prefix

elf/elf.go, elf/module.go
Before closing the file descriptors of the perf ring buffer it is needed to
unmap and disable them.
https://github.com/iovisor/bcc/blob/d147588ebe35b7cd2b4d253a7da18bef253ea78d/src/cc/perf_reader.c#L69
=> add missing call to unmap and disable when freeing a perf ring buffer

elf/elf.go, elf/include/uapi/linux/perf_event.h, elf/perf.go
Useful for overwritable ring buffers which hold the last entries written. They should be stopped before being dumped due to their nature of overwriting their oldest entries. Backwards dumping
starts with the newest entry.
-----
Supersedes: https://github.com/iovisor/gobpf/pull/187
cc @pothos @mauriciovasquezbernal
=> Implement backward & overwriteable ring buffers

elf/elf.go
The logic to close tracepoint programs was closing the STDIN file descriptor
because an initialization to -1 was missing.
Signed-off-by: Mauricio Vásquez <mauricio@kinvolk.io>
=> elf: Fix closing tracepoint programs

bcc/perf.go
Fixes #272 
`lostCallback` is exported via CGO and re-imported elsewhere as a C function.
The second argument is declared as uint64_t when re-imported, but declared
as unsigned long in the original Go function definition.  These two types
are not the same size on all architectures, and cause build failures on
systems where the types mismatch.
This commit changes the original function definition of lostCallback to
use the type C.uint64_t instead of C.ulong for the second argument, to
maintain compatibility across architectures.
=> Use exact width integer argument to lostCallback. 

bcc/table.go, pkg/cpuonline/cpuonline.go, pkg/cpupossible/cpupossible.go, pkg/cpurange/cpu_range.go, pkg/cpurange/cpu_range_test.go
When accessing an eBPF map element, `gobpf` currently allocates a slice to store one value of that map.
It then calls `bpf_lookup_elem()` to get the element of the map.
But in the case of `PERCPU_XXX` maps, `bpf_lookup_elem()` writes an *array* of values with as many elements as the number of possible CPUs.
This led to an out-of-bounds write.
=> Fix memory corruption when reading PERCPU_XXX maps

bcc/table.go
C.ulong isn't defined for 32-bit arches. Use C.size_t instead.
Signed-off-by: Lokesh Mandvekar <lsm5@fedoraproject.org>
oci-seccomp-bpf-hook vendors this repo and 32-bit builds are failing on fedora. See failure log for armv7hl:
https://koji.fedoraproject.org/koji/getfile?taskID=66857102&volume=DEFAULT&name=build.log&offset=-4000
/cc @vrothberg @ashcrow
=> Fix build on 32-bit arches
