COPYRIGHT.txt
examples/perf.go
perf.go

Signed-off-by: Michael Schubert <michael@kinvolk.io>

Basic PerfMap implementation

---

bpf_test.go
elf/elf.go
elf/kernel_version.go
elf/kernel_version_test.go

Signed-off-by: Michael Schubert <michael@kinvolk.io>

elf: special case current version for Ubuntu/Debian

---

elf/module.go

Signed-off-by: Michael Schubert <michael@kinvolk.io>

elf: add helper `EnableKprobes()`

---

elf/elf.go
elf/elf_unsupported.go
elf/kernel_version.go
elf/kernel_version_test.go
elf/module.go
elf/perf.go
elf/table.go
elf/utsname_int8.go
elf/utsname_uint8.go

So we can (at least) build in other architectures.

Fixes for other architectures

---

elf/elf_unsupported.go

Use the correct package

---

elf/elf_unsupported.go
elf/module_unsupported.go
elf/perf_unsupported.go

Add missing unsupported functions/structures

---

elf/perf.go

Before this patch, the perf events reordering code was assuming that
there was a timestamp in the first field of the perf event struct. That
convention was not explicit.
This patch removes this assumption: by default, perf events are not
ordered unless SetGetTimestamp() is called to register a callback
getting the timestamp.
-----
This patch was tested with the branch https://github.com/kinvolk/scope/tree/alban/reordering-api
@iaguis @schu @alepuccetti PTAL

perf event reordering: improve API

---

bcc/perf.go

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x556edd8ee96e]
```
goroutine 9 [running]:
panic(0x556edd94e940, 0xc42000c140)
/usr/lib/go-1.7/src/runtime/panic.go:500 +0x1a1
github.com/iovisor/gobpf/bcc.callback_to_go(0xc42000c5c8, 0x7f45b4bee24c, 0xc400000114)
/go/src/github.com/iovisor/gobpf/bcc/perf.go:92 +0x4e
github.com/iovisor/gobpf/bcc._cgoexpwrap_9ea30c17befe_callback_to_go(0xc42000c5c8, 0x7f45b4bee24c, 0xc400000114)
??:0 +0x3d
github.com/iovisor/gobpf/bcc._Cfunc_perf_reader_poll(0x556e00000004, 0xc420014220, 0xc4000001f4, 0x0)
??:0 +0x4d
github.com/iovisor/gobpf/bcc.(*PerfMap).poll(0xc420016540, 0x1f4)
/go/src/github.com/iovisor/gobpf/bcc/perf.go:168 +0x13c
created by …
```

bcc/perf: fix panic invalid memory address

---

elf/elf.go
elf/module.go

A module can now be created from a file name or from a reader.
@schu @iaguis PTAL

elf: add NewModuleFromReader

---

elf/elf.go

elf: don't assume all maps are perf maps

---

bcc/perf.go
bcc/table.go
elf/elf.go

We weren't printing errno for some errors.

bcc,elf: improve errors

---

elf/elf.go
elf/include/bpf.h
elf/module.go
elf/module_unsupported.go

Add include/bpf.h to get the new bpf types.

elf: add support for cgroup/skb and cgroup/sock

---

bcc/module.go

Resubmit the PR based on the comment. 
@schu

Fix bpf_detach_kprobe call for bcc 0.3.0

---

tracepipe/trace_pipe.go
tracepipe/trace_pipe_test.go

tracepipe: fix case with ':' in message

---

elf/module.go

Pinned maps now need to be unpinned explicitly by setting `Unpin` in the
`CloseOptions` and using `CloseExt`.

elf: add `CloseExt`

---

elf/perf.go

Fixes https://github.com/iovisor/gobpf/issues/69

perf: close go channels idiomatically

---

examples/bcc/bash_readline/bash_readline.go

Avoid having padding null chars by using u32/uint32 consistently for the
PID and by packing the struct.
Also remove the unnecessary import "C", the example itself is not using
any cgo.
Signed-off-by: Tobias Klauser <tklauser@distanz.ch>

examples: avoid padding null bytes in command string

---

bcc/module.go

This PR fixes a few minor issues regarding returned errors. Please see the individual commit messages for details.

Error message fixes

---

bcc/module.go
examples/bcc/xdp/xdp_drop.go

Hi. Congrats for the great work so far.
This PR adds XDP support based on the python-bcc lib.
Please let me know if there's any change to be made.

Added XDP support

---

pkg/progtestrun/prog_test_run.go

Add pkg/progtestrun for BPF_PROG_TEST_RUN

---

bcc/module.go

Same comment applies: https://github.com/iovisor/gobpf/pull/118#issuecomment-387263354.
I have a use-case PR ready for this too: https://github.com/cloudflare/ebpf_exporter/pull/16.

Add support for perf events

---

bcc/perf.go
examples/bcc/execsnoop/execsnoop.go
examples/bcc/execsnoop/output.go

Hi!
This is a port of BCC's execsnoop in Go. It also adds a new flag to
output the events as json strings.
I'll really appreciate your feedback :wave:
Signed-off-by: David Calavera <david.calavera@gmail.com>

Implement execsnoop.

---

elf/pinning.go

pinning: fix error message format string

---

elf/elf.go

related issue #195 
Signed-off-by: forrestchen <forrestchen@tencent.com>

set map_flags in bpf_attr when call BPF_MAP_CREATE

---

elf/elf_unsupported.go
elf/errno.go
elf/module_unsupported.go
elf/perf_unsupported.go

For building module in the unsupported platform.

elf: add dummy implementations for module_unsupported

---

bcc/module.go

bcc: update bpf_module_create_c_from_string for bcc 0.11.0 (fixes #202)

---

README.md

This PR proposes some minor changes to the README to improve its quality and readability.

Improve phrasing in README

---

bcc/perf.go

This PR introduces a new exported function InitPerfMapWithPageCnt which allows programs that use this library to configure the size of the ring buffer.  The approach of using a new method is to not break API stability with older clients.
Addresses #156
References: https://github.com/iovisor/bcc/pull/997

Configurable Page Count when creating PerfMaps

---

bcc/perf.go

this is a followup for https://github.com/iovisor/gobpf/pull/218 where the original author did not address the review comment.

fix pageCnt error message

---

elf/elf.go
elf/include/doc.go
elf/include/libbpf.h
elf/include/uapi/linux/doc.go
elf/module.go
elf/netlink.c
elf/nlattr.c

Co-authored-by: Tamal Saha <tamal@appscode.com>

Add doc.go so go mod keeps this folder
